---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: object-detection-r1731945034003
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: object-detection-r1731945034003 
  name: object-detection-r1731945034003
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi