apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: object-detection-r1731945034003
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: object-detection-r1731945034003 
  name: object-detection-r1731945034003
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: object-detection-r1731945034003 
    weight: 100 
  wildcardPolicy: None
