apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: object-detection-r1731945034003
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: object-detection-r1731945034003 
  name: object-detection-r1731945034003
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: object-detection-r1731945034003 
